export default {
    dt: {
        "code": 0,
        "msg": "",
        "data": {
          "appInstallsLists": [
            {
              "fbAppId": "985920648140845",
              "appName": "111",
              "installsNum": 11774,
              "per": "0.98"
            },
            {
              "fbAppId": "1659326484353391",
              "appName": "222",
              "installsNum": 172,
              "per": "0.01"
            },
            {
              "fbAppId": "329006174266183",
              "appName": "333",
              "installsNum": 37,
              "per": "0.00"
            },
            {
              "fbAppId": "731569850347968",
              "appName": "444",
              "installsNum": 24,
              "per": "0.00"
            },
            {
              "fbAppId": "1046543482157683",
              "appName": "555",
              "installsNum": 3,
              "per": "0.00"
            }
          ],
          "appSpendDatasLists": [
            {
              "fbAppId": "985920648140845",
              "appName": "111",
              "spend": 35849.23,
              "per": "0.98"
            },
            {
              "fbAppId": "1659326484353391",
              "appName": "222",
              "spend": 493.56,
              "per": "0.01"
            },
            {
              "fbAppId": "329006174266183",
              "appName": "333",
              "spend": 122.03,
              "per": "0.00"
            },
            {
              "fbAppId": "731569850347968",
              "appName": "444",
              "spend": 62.73,
              "per": "0.00"
            },
            {
              "fbAppId": "1046543482157683",
              "appName": "555",
              "spend": 13.49,
              "per": "0.00"
            }
          ],
          "todayInstallsNum": null,
          "todaySpend": null,
          "yesdayInstallsNum": null,
          "yesdaySpend": null,
          "insightDate": null,
          "reportAppDataList": [
            {
              "fbAppId": "1046543482157683",
              "appName": "",
              "reachNum": 3393,
              "showNum": 4331,
              "clicksNum": 89,
              "installsNum": 3,
              "spend": 13.49,
              "relevanceScore": 0,
              "ctr": "2.05%",
              "cvr": "3.37%",
              "cpm": 3.11,
              "cpc": 0.15,
              "cpi": 4.5
            },
            {
              "fbAppId": "1659326484353391",
              "appName": "",
              "reachNum": 66496,
              "showNum": 74750,
              "clicksNum": 3352,
              "installsNum": 172,
              "spend": 493.56,
              "relevanceScore": 0,
              "ctr": "4.48%",
              "cvr": "5.13%",
              "cpm": 6.6,
              "cpc": 0.15,
              "cpi": 2.87
            },
            {
              "fbAppId": "329006174266183",
              "appName": "",
              "reachNum": 18787,
              "showNum": 19367,
              "clicksNum": 593,
              "installsNum": 37,
              "spend": 122.03,
              "relevanceScore": 0,
              "ctr": "3.06%",
              "cvr": "6.24%",
              "cpm": 6.3,
              "cpc": 0.21,
              "cpi": 3.3
            },
            {
              "fbAppId": "731569850347968",
              "appName": "",
              "reachNum": 5140,
              "showNum": 5515,
              "clicksNum": 246,
              "installsNum": 24,
              "spend": 62.73,
              "relevanceScore": 0,
              "ctr": "4.46%",
              "cvr": "9.76%",
              "cpm": 11.37,
              "cpc": 0.26,
              "cpi": 2.61
            },
            {
              "fbAppId": "985920648140845",
              "appName": "",
              "reachNum": 4429480,
              "showNum": 4697303,
              "clicksNum": 186398,
              "installsNum": 11774,
              "spend": 35849.23,
              "relevanceScore": 0,
              "ctr": "3.97%",
              "cvr": "6.32%",
              "cpm": 7.63,
              "cpc": 0.19,
              "cpi": 3.04
            }
          ]
        }
      },
      dt2: {
        "code": 0,
        "msg": "",
        "data": {
          "pageNum": 1,
          "pageSize": 20,
          "size": 0,
          "startRow": 0,
          "endRow": 0,
          "total": 32,
          "pages": 0,
          "list": [
            {
              "id": null,
              "reachNum": null,
              "showNum": null,
              "clicksNum": null,
              "installsNum": 218,
              "spend": 581.33,
              "relevanceScore": null,
              "country": "US",
              "userOs": "Android",
              "fbApplicationId": null,
              "applicationName": null,
              "insightDate": 1528214400000,
              "fbCreateTime": null,
              "updateTime": null,
              "fbAdsetId": null,
              "ctr": null,
              "cvr": null,
              "cpm": null,
              "cpc": null,
              "cpi": 2.67,
              "startDate": null,
              "endDate": null,
              "pageStart": null,
              "pageSize": null,
              "pageNo": null,
              "orderByClause": null
            },
            {
              "id": null,
              "reachNum": null,
              "showNum": null,
              "clicksNum": null,
              "installsNum": 470,
              "spend": 1351.06,
              "relevanceScore": null,
              "country": "US",
              "userOs": "Android",
              "fbApplicationId": null,
              "applicationName": null,
              "insightDate": 1528646400000,
              "fbCreateTime": null,
              "updateTime": null,
              "fbAdsetId": null,
              "ctr": null,
              "cvr": null,
              "cpm": null,
              "cpc": null,
              "cpi": 2.87,
              "startDate": null,
              "endDate": null,
              "pageStart": null,
              "pageSize": null,
              "pageNo": null,
              "orderByClause": null
            },
            {
              "id": null,
              "reachNum": null,
              "showNum": null,
              "clicksNum": null,
              "installsNum": 84,
              "spend": 270.36,
              "relevanceScore": null,
              "country": "US",
              "userOs": "Android",
              "fbApplicationId": null,
              "applicationName": null,
              "insightDate": 1528819200000,
              "fbCreateTime": null,
              "updateTime": null,
              "fbAdsetId": null,
              "ctr": null,
              "cvr": null,
              "cpm": null,
              "cpc": null,
              "cpi": 3.22,
              "startDate": null,
              "endDate": null,
              "pageStart": null,
              "pageSize": null,
              "pageNo": null,
              "orderByClause": null
            },
            {
              "id": null,
              "reachNum": null,
              "showNum": null,
              "clicksNum": null,
              "installsNum": 145,
              "spend": 408.79,
              "relevanceScore": null,
              "country": "US",
              "userOs": "Android",
              "fbApplicationId": null,
              "applicationName": null,
              "insightDate": 1528905600000,
              "fbCreateTime": null,
              "updateTime": null,
              "fbAdsetId": null,
              "ctr": null,
              "cvr": null,
              "cpm": null,
              "cpc": null,
              "cpi": 2.82,
              "startDate": null,
              "endDate": null,
              "pageStart": null,
              "pageSize": null,
              "pageNo": null,
              "orderByClause": null
            },
            {
              "id": null,
              "reachNum": null,
              "showNum": null,
              "clicksNum": null,
              "installsNum": 207,
              "spend": 596.94,
              "relevanceScore": null,
              "country": "US",
              "userOs": "Android",
              "fbApplicationId": null,
              "applicationName": null,
              "insightDate": 1528992000000,
              "fbCreateTime": null,
              "updateTime": null,
              "fbAdsetId": null,
              "ctr": null,
              "cvr": null,
              "cpm": null,
              "cpc": null,
              "cpi": 2.88,
              "startDate": null,
              "endDate": null,
              "pageStart": null,
              "pageSize": null,
              "pageNo": null,
              "orderByClause": null
            },
            {
              "id": null,
              "reachNum": null,
              "showNum": null,
              "clicksNum": null,
              "installsNum": 386,
              "spend": 1092.36,
              "relevanceScore": null,
              "country": "US",
              "userOs": "Android",
              "fbApplicationId": null,
              "applicationName": null,
              "insightDate": 1529078400000,
              "fbCreateTime": null,
              "updateTime": null,
              "fbAdsetId": null,
              "ctr": null,
              "cvr": null,
              "cpm": null,
              "cpc": null,
              "cpi": 2.83,
              "startDate": null,
              "endDate": null,
              "pageStart": null,
              "pageSize": null,
              "pageNo": null,
              "orderByClause": null
            },
            {
              "id": null,
              "reachNum": null,
              "showNum": null,
              "clicksNum": null,
              "installsNum": 606,
              "spend": 1750.89,
              "relevanceScore": null,
              "country": "US",
              "userOs": "Android",
              "fbApplicationId": null,
              "applicationName": null,
              "insightDate": 1529164800000,
              "fbCreateTime": null,
              "updateTime": null,
              "fbAdsetId": null,
              "ctr": null,
              "cvr": null,
              "cpm": null,
              "cpc": null,
              "cpi": 2.89,
              "startDate": null,
              "endDate": null,
              "pageStart": null,
              "pageSize": null,
              "pageNo": null,
              "orderByClause": null
            },
            {
              "id": null,
              "reachNum": null,
              "showNum": null,
              "clicksNum": null,
              "installsNum": 632,
              "spend": 1834.67,
              "relevanceScore": null,
              "country": "US",
              "userOs": "Android",
              "fbApplicationId": null,
              "applicationName": null,
              "insightDate": 1529251200000,
              "fbCreateTime": null,
              "updateTime": null,
              "fbAdsetId": null,
              "ctr": null,
              "cvr": null,
              "cpm": null,
              "cpc": null,
              "cpi": 2.9,
              "startDate": null,
              "endDate": null,
              "pageStart": null,
              "pageSize": null,
              "pageNo": null,
              "orderByClause": null
            },
            {
              "id": null,
              "reachNum": null,
              "showNum": null,
              "clicksNum": null,
              "installsNum": 520,
              "spend": 1556.46,
              "relevanceScore": null,
              "country": "US",
              "userOs": "Android",
              "fbApplicationId": null,
              "applicationName": null,
              "insightDate": 1529337600000,
              "fbCreateTime": null,
              "updateTime": null,
              "fbAdsetId": null,
              "ctr": null,
              "cvr": null,
              "cpm": null,
              "cpc": null,
              "cpi": 2.99,
              "startDate": null,
              "endDate": null,
              "pageStart": null,
              "pageSize": null,
              "pageNo": null,
              "orderByClause": null
            },
            {
              "id": null,
              "reachNum": null,
              "showNum": null,
              "clicksNum": null,
              "installsNum": 476,
              "spend": 1399.58,
              "relevanceScore": null,
              "country": "US",
              "userOs": "Android",
              "fbApplicationId": null,
              "applicationName": null,
              "insightDate": 1529424000000,
              "fbCreateTime": null,
              "updateTime": null,
              "fbAdsetId": null,
              "ctr": null,
              "cvr": null,
              "cpm": null,
              "cpc": null,
              "cpi": 2.94,
              "startDate": null,
              "endDate": null,
              "pageStart": null,
              "pageSize": null,
              "pageNo": null,
              "orderByClause": null
            },
            {
              "id": null,
              "reachNum": null,
              "showNum": null,
              "clicksNum": null,
              "installsNum": 403,
              "spend": 1152,
              "relevanceScore": null,
              "country": "US",
              "userOs": "Android",
              "fbApplicationId": null,
              "applicationName": null,
              "insightDate": 1529510400000,
              "fbCreateTime": null,
              "updateTime": null,
              "fbAdsetId": null,
              "ctr": null,
              "cvr": null,
              "cpm": null,
              "cpc": null,
              "cpi": 2.86,
              "startDate": null,
              "endDate": null,
              "pageStart": null,
              "pageSize": null,
              "pageNo": null,
              "orderByClause": null
            },
            {
              "id": null,
              "reachNum": null,
              "showNum": null,
              "clicksNum": null,
              "installsNum": 283,
              "spend": 822.55,
              "relevanceScore": null,
              "country": "US",
              "userOs": "Android",
              "fbApplicationId": null,
              "applicationName": null,
              "insightDate": 1529596800000,
              "fbCreateTime": null,
              "updateTime": null,
              "fbAdsetId": null,
              "ctr": null,
              "cvr": null,
              "cpm": null,
              "cpc": null,
              "cpi": 2.91,
              "startDate": null,
              "endDate": null,
              "pageStart": null,
              "pageSize": null,
              "pageNo": null,
              "orderByClause": null
            },
            {
              "id": null,
              "reachNum": null,
              "showNum": null,
              "clicksNum": null,
              "installsNum": 276,
              "spend": 860.31,
              "relevanceScore": null,
              "country": "US",
              "userOs": "Android",
              "fbApplicationId": null,
              "applicationName": null,
              "insightDate": 1529683200000,
              "fbCreateTime": null,
              "updateTime": null,
              "fbAdsetId": null,
              "ctr": null,
              "cvr": null,
              "cpm": null,
              "cpc": null,
              "cpi": 3.12,
              "startDate": null,
              "endDate": null,
              "pageStart": null,
              "pageSize": null,
              "pageNo": null,
              "orderByClause": null
            },
            {
              "id": null,
              "reachNum": null,
              "showNum": null,
              "clicksNum": null,
              "installsNum": 244,
              "spend": 711.56,
              "relevanceScore": null,
              "country": "US",
              "userOs": "Android",
              "fbApplicationId": null,
              "applicationName": null,
              "insightDate": 1529769600000,
              "fbCreateTime": null,
              "updateTime": null,
              "fbAdsetId": null,
              "ctr": null,
              "cvr": null,
              "cpm": null,
              "cpc": null,
              "cpi": 2.92,
              "startDate": null,
              "endDate": null,
              "pageStart": null,
              "pageSize": null,
              "pageNo": null,
              "orderByClause": null
            },
            {
              "id": null,
              "reachNum": null,
              "showNum": null,
              "clicksNum": null,
              "installsNum": 331,
              "spend": 942.36,
              "relevanceScore": null,
              "country": "US",
              "userOs": "Android",
              "fbApplicationId": null,
              "applicationName": null,
              "insightDate": 1529856000000,
              "fbCreateTime": null,
              "updateTime": null,
              "fbAdsetId": null,
              "ctr": null,
              "cvr": null,
              "cpm": null,
              "cpc": null,
              "cpi": 2.85,
              "startDate": null,
              "endDate": null,
              "pageStart": null,
              "pageSize": null,
              "pageNo": null,
              "orderByClause": null
            },
            {
              "id": null,
              "reachNum": null,
              "showNum": null,
              "clicksNum": null,
              "installsNum": 195,
              "spend": 563.93,
              "relevanceScore": null,
              "country": "US",
              "userOs": "Android",
              "fbApplicationId": null,
              "applicationName": null,
              "insightDate": 1529942400000,
              "fbCreateTime": null,
              "updateTime": null,
              "fbAdsetId": null,
              "ctr": null,
              "cvr": null,
              "cpm": null,
              "cpc": null,
              "cpi": 2.89,
              "startDate": null,
              "endDate": null,
              "pageStart": null,
              "pageSize": null,
              "pageNo": null,
              "orderByClause": null
            },
            {
              "id": null,
              "reachNum": null,
              "showNum": null,
              "clicksNum": null,
              "installsNum": 96,
              "spend": 289.94,
              "relevanceScore": null,
              "country": "US",
              "userOs": "Android",
              "fbApplicationId": null,
              "applicationName": null,
              "insightDate": 1530028800000,
              "fbCreateTime": null,
              "updateTime": null,
              "fbAdsetId": null,
              "ctr": null,
              "cvr": null,
              "cpm": null,
              "cpc": null,
              "cpi": 3.02,
              "startDate": null,
              "endDate": null,
              "pageStart": null,
              "pageSize": null,
              "pageNo": null,
              "orderByClause": null
            },
            {
              "id": null,
              "reachNum": null,
              "showNum": null,
              "clicksNum": null,
              "installsNum": 93,
              "spend": 271.67,
              "relevanceScore": null,
              "country": "US",
              "userOs": "Android",
              "fbApplicationId": null,
              "applicationName": null,
              "insightDate": 1530115200000,
              "fbCreateTime": null,
              "updateTime": null,
              "fbAdsetId": null,
              "ctr": null,
              "cvr": null,
              "cpm": null,
              "cpc": null,
              "cpi": 2.92,
              "startDate": null,
              "endDate": null,
              "pageStart": null,
              "pageSize": null,
              "pageNo": null,
              "orderByClause": null
            },
            {
              "id": null,
              "reachNum": null,
              "showNum": null,
              "clicksNum": null,
              "installsNum": 210,
              "spend": 624.16,
              "relevanceScore": null,
              "country": "US",
              "userOs": "Android",
              "fbApplicationId": null,
              "applicationName": null,
              "insightDate": 1530201600000,
              "fbCreateTime": null,
              "updateTime": null,
              "fbAdsetId": null,
              "ctr": null,
              "cvr": null,
              "cpm": null,
              "cpc": null,
              "cpi": 2.97,
              "startDate": null,
              "endDate": null,
              "pageStart": null,
              "pageSize": null,
              "pageNo": null,
              "orderByClause": null
            },
            {
              "id": null,
              "reachNum": null,
              "showNum": null,
              "clicksNum": null,
              "installsNum": 236,
              "spend": 691.98,
              "relevanceScore": null,
              "country": "US",
              "userOs": "Android",
              "fbApplicationId": null,
              "applicationName": null,
              "insightDate": 1530288000000,
              "fbCreateTime": null,
              "updateTime": null,
              "fbAdsetId": null,
              "ctr": null,
              "cvr": null,
              "cpm": null,
              "cpc": null,
              "cpi": 2.93,
              "startDate": null,
              "endDate": null,
              "pageStart": null,
              "pageSize": null,
              "pageNo": null,
              "orderByClause": null
            }
          ],
          "prePage": 0,
          "nextPage": 0,
          "isFirstPage": false,
          "isLastPage": false,
          "hasPreviousPage": false,
          "hasNextPage": false,
          "navigatePages": 0,
          "navigatepageNums": null,
          "navigateFirstPage": 0,
          "navigateLastPage": 0,
          "lastPage": 0,
          "firstPage": 0
        }
      }
}